import re
import json

class JavaCodeGenerator:
    """
    Generates enterprise-grade Java + Selenium + TestNG automation code
    adhering to Page Object Model (POM) design patterns.
    """

    JAVA_KEYWORDS = {
        "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
        "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float",
        "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native",
        "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp",
        "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void",
        "volatile", "while", "true", "false", "null"
    }

    @staticmethod
    def sanitize_method_name(raw_name, fallback_prefix="test_step"):
        """Ensures method name is a valid Java identifier and not a reserved keyword."""
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', str(raw_name).strip())
        clean = re.sub(r'_+', '_', clean).strip('_')
        if not clean or clean[0].isdigit():
            clean = f"{fallback_prefix}_{clean}"
        if clean.lower() in JavaCodeGenerator.JAVA_KEYWORDS:
            clean = f"{fallback_prefix}_{clean}"
        return clean[:45]

    @staticmethod
    def generate_testng_class(suite_name="EcommerceRegressionSuite", test_cases=None):
        if test_cases is None:
            test_cases = []

        java_methods = []
        for i, tc in enumerate(test_cases, 1):
            method_name = JavaCodeGenerator.sanitize_method_name(tc.get("title", f"test_{i}"), f"test_{i}")
            priority = 1 if tc.get("priority") == "High" else (0 if tc.get("priority") == "Critical" else 2)
            description = tc.get("title", "").replace('"', '\\"').replace('\n', ' ')

            steps = tc.get("steps_json", [])
            if isinstance(steps, str):
                try:
                    steps = json.loads(steps)
                except:
                    steps = []

            step_calls = []
            for s in steps:
                action = s.get("action", "").lower().strip()
                target = s.get("target", "").replace('"', '\\"')
                val = s.get("value", "").replace('"', '\\"')
                if action == "navigate":
                    step_calls.append(f'        driver.get(baseUrl + "{target}");')
                elif action == "click":
                    step_calls.append(f'        wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("{target}"))).click();')
                elif action == "input":
                    step_calls.append(f'        WebElement input = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("{target}")));\n        input.clear();\n        input.sendKeys("{val}");')
                elif action == "assert_text":
                    step_calls.append(f'        WebElement elem = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("{target}")));\n        Assert.assertTrue(elem.getText().contains("{val}"), "Expected text not found in element");')
                elif action == "assert_visible":
                    step_calls.append(f'        Assert.assertTrue(wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("{target}"))).isDisplayed(), "Element should be visible");')

            if not step_calls:
                step_calls.append(f'        // Automated verification for: {description}')
                step_calls.append('        driver.get(baseUrl + "/app/target-store");')
                step_calls.append('        Assert.assertTrue(driver.getTitle().length() > 0, "Page title should be non-empty");')

            steps_code = "\n".join(step_calls)

            method_code = f"""    @Test(priority = {priority}, description = "{description}")
    public void {method_name}() {{
{steps_code}
    }}"""
            java_methods.append(method_code)

        all_methods_code = "\n\n".join(java_methods)
        clean_class_name = JavaCodeGenerator.sanitize_method_name(suite_name, "RegressionSuite").capitalize()

        full_class = f"""package com.qaplatform.tests;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import java.time.Duration;

/**
 * Auto-generated by AI-Powered QA Testing Assistant Platform
 * Suite: {suite_name}
 */
public class {clean_class_name}Test {{

    private WebDriver driver;
    private WebDriverWait wait;
    private final String baseUrl = System.getProperty("baseUrl", "http://127.0.0.1:5000");

    @BeforeMethod
    public void setUp() {{
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless=new", "--disable-gpu", "--no-sandbox", "--window-size=1280,800");
        driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(2));
        wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    }}

{all_methods_code}

    @AfterMethod
    public void tearDown() {{
        if (driver != null) {{
            driver.quit();
        }}
    }}
}}
"""
        return full_class

    @staticmethod
    def generate_pom_login_class():
        return """package com.qaplatform.pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;

public class LoginPage extends BasePage {
    private final By loginBtnNav = By.id("nav-login-btn");
    private final By emailField = By.id("login-email");
    private final By passwordField = By.id("login-password");
    private final By submitBtn = By.id("login-submit-btn");
    private final By errorAlert = By.id("login-error-alert");
    private final By userBadge = By.id("user-profile-badge");

    public LoginPage(WebDriver driver) {
        super(driver);
    }

    public void openLoginModal() {
        click(loginBtnNav);
    }

    public void login(String email, String password) {
        openLoginModal();
        type(emailField, email);
        type(passwordField, password);
        click(submitBtn);
    }

    public boolean isUserLoggedIn() {
        return isElementDisplayed(userBadge);
    }

    public String getErrorMessage() {
        return getText(errorAlert);
    }
}
"""

    @staticmethod
    def generate_maven_pom():
        return """<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.qaplatform</groupId>
    <artifactId>qa-automation-assistant</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <selenium.version>4.18.1</selenium.version>
        <testng.version>7.9.0</testng.version>
        <webdrivermanager.version>5.7.0</webdrivermanager.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>
    </dependencies>
</project>
"""

    @staticmethod
    def generate_python_pytest(test_cases=None):
        if test_cases is None:
            test_cases = []

        code = """import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

@pytest.fixture(scope="module")
def driver():
    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-gpu")
    driver = webdriver.Chrome(options=options)
    yield driver
    driver.quit()

BASE_URL = "http://127.0.0.1:5000"
"""
        for i, tc in enumerate(test_cases, 1):
            method_name = JavaCodeGenerator.sanitize_method_name(tc.get("title", f"test_{i}"), f"test_{i}").lower()
            code += f"""
def test_{method_name}(driver):
    \"\"\"{tc.get('title', '')}\"\"\"
    driver.get(f"{{BASE_URL}}/app/target-store")
    wait = WebDriverWait(driver, 5)
    assert wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
"""
        return code

java_generator = JavaCodeGenerator()
